version: '3'

services:

  mongodb:
    image: mongo:latest
    container_name: phone_validation_service_db
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - phone-validation-service-data:/data/db
      - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh

volumes:
  phone-validation-service-data:
